FROM python:3.13-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*


COPY . /app

WORKDIR /app
RUN uv sync --frozen --no-cache

ENV PYTHONUNBUFFERED=1