services:
  proxy:
    image: nginx:1.29-alpine
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ../proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./certs:/etc/nginx/certs:ro # HTTPS
    depends_on:
      - auth_api
    networks:
      - proxy_network